In [1]:
!pip install numpy

In [9]:
import numpy as np

CREATING AN ARRAY AND IT'S METHODS!

In [3]:
#creating an array

arr = np.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.shape

(6,)

In [8]:
arr.size

6

In [10]:
arr = np.array([[1, 2], [3, 4]])

In [11]:
arr

array([[1, 2],
       [3, 4]])

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr.ndim

2

In [14]:
arr = np.zeros((2,4))

In [15]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr = np.ones((2,4))

In [17]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr = np.full((2,4),3)

In [19]:
arr

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [20]:
arr = np.eye(2)

In [21]:
arr

array([[1., 0.],
       [0., 1.]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

RANDOM ARRAYS

In [25]:
arr = np.random.seed(10) 

In [29]:
np.random.randint(1, 10, size=(3,3))

array([[5, 4, 1],
       [5, 7, 9],
       [2, 9, 5]], dtype=int32)

INDEXING AND SLICING

In [30]:
arr = np.random.randint(1, 20, size=(4,3))

In [31]:
arr

array([[15, 18, 14],
       [ 6, 14, 14],
       [13,  2,  5],
       [19, 14, 12]], dtype=int32)

In [32]:
arr[0]

array([15, 18, 14], dtype=int32)

In [33]:
arr[0:]

array([[15, 18, 14],
       [ 6, 14, 14],
       [13,  2,  5],
       [19, 14, 12]], dtype=int32)

In [39]:
arr[1:3][0:2]

array([[ 6, 14, 14],
       [13,  2,  5]], dtype=int32)

In [ ]:
#reverses an array

arr[0, ::-1]

array([14, 18, 15], dtype=int32)

In [43]:
arr.flatten()

array([15, 18, 14,  6, 14, 14, 13,  2,  5, 19, 14, 12], dtype=int32)

In [44]:
arr[arr > 10]

array([15, 18, 14, 14, 14, 13, 19, 14, 12], dtype=int32)

In [45]:
arr

array([[15, 18, 14],
       [ 6, 14, 14],
       [13,  2,  5],
       [19, 14, 12]], dtype=int32)

In [ ]:
#arr.reshape is to be done according to the exact size of the array you want to reshape

arr.reshape((2,6))

array([[15, 18, 14,  6, 14, 14],
       [13,  2,  5, 19, 14, 12]], dtype=int32)

In [49]:
arr

array([[15, 18, 14],
       [ 6, 14, 14],
       [13,  2,  5],
       [19, 14, 12]], dtype=int32)

In [ ]:
#arr.T or arr.transpose() both are same.They convert columns -> rows

arr.T

array([[15,  6, 13, 19],
       [18, 14,  2, 14],
       [14, 14,  5, 12]], dtype=int32)

VECTORIZATION

In [51]:
arr 


array([[15, 18, 14],
       [ 6, 14, 14],
       [13,  2,  5],
       [19, 14, 12]], dtype=int32)

In [55]:
arr.flatten()

array([15, 18, 14,  6, 14, 14, 13,  2,  5, 19, 14, 12], dtype=int32)

In [56]:
arr += 2

In [57]:
arr

array([[17, 20, 16],
       [ 8, 16, 16],
       [15,  4,  7],
       [21, 16, 14]], dtype=int32)

In [63]:
arr = np.random.randint(1,10,size=(4,4))

In [64]:
arr

array([[6, 5, 8, 9],
       [9, 3, 7, 3],
       [9, 9, 7, 7],
       [6, 7, 1, 1]], dtype=int32)

Vectorized operations don't just have less Python code — they hand the whole loop to pre-compiled C code under the hood, where it runs without the interpreter's per-element overhead.

In [ ]:
arr * 2

array([[12, 10, 16, 18],
       [18,  6, 14,  6],
       [18, 18, 14, 14],
       [12, 14,  2,  2]], dtype=int32)

Broadcasting

Vectorized operations are easy when both arrays are the same shape. Broadcasting is what happens when they're not — and NumPy still finds a way.

In [67]:
grid = np.ones((3, 4))
row = np.array([1, 2, 3, 4])
print(grid + row)  # row is applied to every row of grid

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


Aggregation Functions

In [68]:
arr

array([[6, 5, 8, 9],
       [9, 3, 7, 3],
       [9, 9, 7, 7],
       [6, 7, 1, 1]], dtype=int32)

In [82]:
arr.sum()
arr.sum(axis=0) # columns
arr.sum(axis=1) # rows


array([28, 22, 32, 15])

In [70]:
arr.mean()

np.float64(6.0625)

In [71]:
np.median(arr)

np.float64(7.0)

In [72]:
arr.std()

np.float64(2.656801413354035)

In [73]:
arr.var()

np.float64(7.05859375)

In [ ]:
#arr.min returns the value that is minimum and arr.argmin return the index that is minimum
arr.min()

np.int32(1)

In [77]:
arr.argmin()
arr.argmax()


np.int64(3)

In [78]:
np.unique(arr)

array([1, 3, 5, 6, 7, 8, 9], dtype=int32)

In [79]:
np.count_nonzero(arr)

np.int64(16)