In [1]:
!pip install numpy


[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

CREATING AN ARRAY AND IT'S METHODS!

In [3]:
#creating an array

arr = np.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.shape

(6,)

In [8]:
arr.size

6

In [9]:
arr = np.array([[1, 2], [3, 4]])

In [10]:
arr

array([[1, 2],
       [3, 4]])

In [11]:
arr.dtype

dtype('int64')

In [12]:
arr.ndim

2

In [13]:
arr = np.zeros((2,4))

In [14]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr = np.ones((2,4))

In [16]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr = np.full((2,4),3)

In [18]:
arr

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [19]:
arr = np.eye(2)

In [20]:
arr

array([[1., 0.],
       [0., 1.]])

In [21]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

RANDOM ARRAYS

In [23]:
arr = np.random.seed(10) 

In [24]:
np.random.randint(1, 10, size=(3,3))

array([[5, 1, 2],
       [1, 2, 9],
       [1, 9, 7]], dtype=int32)

INDEXING AND SLICING

In [25]:
arr = np.random.randint(1, 20, size=(4,3))

In [26]:
arr

array([[ 5, 17,  5],
       [16, 12, 12],
       [ 2,  9,  5],
       [15, 18, 14]], dtype=int32)

In [27]:
arr[0]

array([ 5, 17,  5], dtype=int32)

In [28]:
arr[0:]

array([[ 5, 17,  5],
       [16, 12, 12],
       [ 2,  9,  5],
       [15, 18, 14]], dtype=int32)

In [29]:
arr[1:3][0:2]

array([[16, 12, 12],
       [ 2,  9,  5]], dtype=int32)

In [30]:
#reverses an array

arr[0, ::-1]

array([ 5, 17,  5], dtype=int32)

In [31]:
arr.flatten()

array([ 5, 17,  5, 16, 12, 12,  2,  9,  5, 15, 18, 14], dtype=int32)

In [32]:
arr[arr > 10]

array([17, 16, 12, 12, 15, 18, 14], dtype=int32)

In [33]:
arr

array([[ 5, 17,  5],
       [16, 12, 12],
       [ 2,  9,  5],
       [15, 18, 14]], dtype=int32)

In [34]:
#arr.reshape is to be done according to the exact size of the array you want to reshape

arr.reshape((2,6))

array([[ 5, 17,  5, 16, 12, 12],
       [ 2,  9,  5, 15, 18, 14]], dtype=int32)

In [35]:
arr

array([[ 5, 17,  5],
       [16, 12, 12],
       [ 2,  9,  5],
       [15, 18, 14]], dtype=int32)

In [36]:
#arr.T or arr.transpose() both are same.They convert columns -> rows

arr.T

array([[ 5, 16,  2, 15],
       [17, 12,  9, 18],
       [ 5, 12,  5, 14]], dtype=int32)

VECTORIZATION

In [37]:
arr 


array([[ 5, 17,  5],
       [16, 12, 12],
       [ 2,  9,  5],
       [15, 18, 14]], dtype=int32)

In [38]:
arr.flatten()

array([ 5, 17,  5, 16, 12, 12,  2,  9,  5, 15, 18, 14], dtype=int32)

In [39]:
arr += 2

In [40]:
arr

array([[ 7, 19,  7],
       [18, 14, 14],
       [ 4, 11,  7],
       [17, 20, 16]], dtype=int32)

In [41]:
arr = np.random.randint(1,10,size=(4,4))

In [42]:
arr

array([[6, 4, 7, 2],
       [5, 3, 7, 8],
       [9, 9, 3, 1],
       [7, 8, 9, 2]], dtype=int32)

Vectorized operations don't just have less Python code — they hand the whole loop to pre-compiled C code under the hood, where it runs without the interpreter's per-element overhead.

In [43]:
arr * 2

array([[12,  8, 14,  4],
       [10,  6, 14, 16],
       [18, 18,  6,  2],
       [14, 16, 18,  4]], dtype=int32)

Broadcasting

Vectorized operations are easy when both arrays are the same shape. Broadcasting is what happens when they're not — and NumPy still finds a way.

In [44]:
grid = np.ones((3, 4))
row = np.array([1, 2, 3, 4])
print(grid + row)  # row is applied to every row of grid

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


Aggregation Functions

In [45]:
arr

array([[6, 4, 7, 2],
       [5, 3, 7, 8],
       [9, 9, 3, 1],
       [7, 8, 9, 2]], dtype=int32)

In [46]:
arr.sum()
arr.sum(axis=0) # columns
arr.sum(axis=1) # rows


array([19, 23, 22, 26])

In [47]:
arr.mean()

np.float64(5.625)

In [48]:
np.median(arr)

np.float64(6.5)

In [49]:
arr.std()

np.float64(2.6896793489187516)

In [50]:
arr.var()

np.float64(7.234375)

In [51]:
#arr.min returns the value that is minimum and arr.argmin return the index that is minimum
arr.min()

np.int32(1)

In [52]:
arr.argmin()
arr.argmax()


np.int64(8)

In [53]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [54]:
np.count_nonzero(arr)

np.int64(16)

In [55]:
arr = np.arange(1,10)

In [56]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr1 = arr.reshape([3,3])

In [65]:
arr2 = np.arange(1,16)

In [70]:
arr2 = arr2.reshape([5,3])

In [73]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [80]:
arr3 = np.arange(11,20)

In [81]:
arr3

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [82]:
arr3 = arr3.reshape([3,3])

In [83]:
arr4 = arr1 + arr3

In [84]:
arr4

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [86]:
arr4.ravel()

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [91]:
arr5 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [92]:
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [93]:
arr5.size

8

In [94]:
arr5.itemsize

8

In [99]:
arr5.ndim

3

In [100]:
arr6 = np.random.randint(0,20,size=(5,4))

In [101]:
arr6

array([[14,  7, 11,  1],
       [ 0, 12,  5,  4],
       [ 7, 18, 12,  2],
       [ 8, 15, 13, 15],
       [ 6, 10, 11, 16]], dtype=int32)

FANCY INDEXING

In [104]:
arr6[1,2]

np.int32(5)

In [105]:
arr6[2:4,1:3]

array([[18, 12],
       [15, 13]], dtype=int32)